- type: entity
  parent: BaseMachineCircuitboard
  id: FabricationManufactorumBoard
  name: manufactorum machine board
  components:
  - type: Sprite
    state: supply
  - type: MachineBoard
    prototype: FabricationManufactorum
    requirements:
      MatterBin: 2
      Manipulator: 1
    materialRequirements:
      Plasteel: 3
      Glass: 2

- type: entity
  parent: BaseMachineCircuitboard
  id: FabricationPharmaceuticalFabricatorBoard
  name: pharmaceutical fabricator machine board
  components:
  - type: Sprite
    state: medical
  - type: MachineBoard
    prototype: FabricationPharmaceuticalFabricator
    requirements:
      MatterBin: 1
      Manipulator: 2
    materialRequirements:
      Plastic: 3
      Glass: 2