- type: entity
  parent: BaseMachineCircuitboard
  id: FabricationPharmaceuticalFabricatorBoard
  name: pharmaceutical fabricator machine board
  components:
  - type: Sprite
    state: medical
  - type: MachineBoard
    prototype: FabricationPharmaceuticalFabricator
    requirements:
      MatterBin: 1
      Manipulator: 2
    materialRequirements:
      Plastic: 3
      Glass: 2

  id: MaterialSiloLoaderCircuitboard
  parent: BaseMachineCircuitboard
  name: material silo loader machine board
  description: A machine printed circuit board for a material silo loader.
  components:
    - type: Sprite
      state: supply
    - type: MachineBoard
      prototype: MaterialSiloLoader
      requirements:
        MatterBin: 2
        Manipulator: 1
      materialRequirements:
        Steel: 5
        Cable: 1
