- type: entity
  parent: BaseMachineCircuitboard
  id: FabricationPharmaceuticalFabricatorBoard
  name: pharmaceutical fabricator machine board
  components:
  - type: Sprite
    state: medical
  - type: MachineBoard
    prototype: FabricationPharmaceuticalFabricator
    requirements:
      MatterBin: 1
      Manipulator: 2
    materialRequirements:
      Plastic: 3
      Glass: 2

