- type: gameMapPool
  id: DefaultMapPool
  maps:
  - Arena
  - Asterisk
  - Core
  - Edge
  - Glacier
  - Hammurabi
  - Lighthouse
  - Pebble
  - Prather
  - Saltern
  - Shoukou
  - Submarine
  - Tortuga
  - TheHive
  - Gax
  - Rad
  - Meta
  - Box
  - Lambda
  - Bagel
  - Northway
#  - Europa
